In [ ]:
#Nimmagadda Shree Deepthi Batch - 37 2303A52303
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load dataset
url = "https://drive.google.com/uc?export=download&id=1AcdENlVm5dccNyo_vgdMbneX8YVvH5R3"
df = pd.read_csv(url)

# Check for non-numeric columns
print(df.dtypes)

# Convert categorical columns to numeric if necessary
for col in df.columns:
    if df[col].dtype == 'object':  # If column is categorical
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])  # Convert text to numbers

# Splitting features and target variable
X = df.iloc[:, :-1].values  # All columns except last
y = df.iloc[:, -1].values  # Target column

# Splitting dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardizing the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Building the ANN Model
model = Sequential([
    Dense(8, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(20, activation='relu'),
    Dense(10, activation='relu'),
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compiling the Model
model.compile(optimizer='adadelta', loss='binary_crossentropy', metrics=['accuracy'])

# Training the Model
model.fit(X_train, y_train, epochs=150, batch_size=64, validation_data=(X_test, y_test))

# Saving the Model
model.save("diabetes_ann_model.h5")

# Loading the Model for Deployment
loaded_model = keras.models.load_model("diabetes_ann_model.h5")

# Making Predictions
y_pred = (loaded_model.predict(X_test) > 0.5).astype(int)

# Performance Metrics
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Test Accuracy: {accuracy * 100:.2f}%")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)


price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 8s 214ms/step - accuracy: 0.3570 - loss: 0.7242 - val_accuracy: 0.2385 - val_loss: 0.7564
Epoch 2/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 94ms/step - accuracy: 0.3245 - loss: 0.7247 - val_accuracy: 0.2385 - val_loss: 0.7563
Epoch 3/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 84ms/step - accuracy: 0.3700 - loss: 0.7229 - val_accuracy: 0.2385 - val_loss: 0.7561
Epoch 4/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 81ms/step - accuracy: 0.3498 - loss: 0.7192 - val_accuracy: 0.2385 - val_loss: 0.7560
Epoch 5/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.3684 - loss: 0.7199 - val_accuracy: 0.2385 - val_loss: 0.7559
Epoch 6/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step - accuracy: 0.3588 - loss: 0.7255 - val_accuracy: 0.2477 - val_loss: 0.7558
Epoch 7/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 0.3580 - loss: 0.7181 - val_accuracy: 0.2477 - val_loss: 0.7557
Epoch 8/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 71ms/step - accuracy: 0.3671 - loss: 0.7185 - val_accuracy: 0.2477 - val_loss

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
Test Accuracy: 23.85%

Confusion Matrix:
[[10 19  0]
 [23 16  0]
 [30 11  0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.16      0.34      0.22        29
           1       0.35      0.41      0.38        39
           2       0.00      0.00      0.00        41

    accuracy                           0.24       109
   macro avg       0.17      0.25      0.20       109
weighted avg       0.17      0.24      0.19       109



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
